/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.tokobuku.view;


import com.mycompany.tokobuku.controller.BukuDAOImp;
import com.mycompany.tokobuku.login.menuStaff;
import com.mycompany.tokobuku.login.menuSupervisor;
import com.mycompany.tokobuku.model.Buku;
import com.mycompany.tokobuku.pdf.BukuPDF;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class FormBuku extends javax.swing.JFrame {

    /**
     * Creates new form FormBuku
     */
    public FormBuku() {
        
        initComponents();
        getCombo();
        showTable();
        this.setTitle("Data Buku");
        combidpenerbit.setSelectedItem(null);
        txtidbuku.setEditable(true);
        //getContentPane().setBackground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtidbuku = new javax.swing.JTextField();
        txtjudul = new javax.swing.JTextField();
        txtpenulis = new javax.swing.JTextField();
        txttahun = new javax.swing.JTextField();
        txtkuantitas = new javax.swing.JTextField();
        txtjenis = new javax.swing.JTextField();
        combidpenerbit = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btntambah = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbuku = new javax.swing.JTable();
        label1 = new javax.swing.JLabel();
        cls = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnreport = new javax.swing.JButton();
        btnback1 = new javax.swing.JButton();
        btnback2 = new javax.swing.JButton();
        btncari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtidbuku.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtjudul.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtpenulis.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txttahun.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtkuantitas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtjenis.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        combidpenerbit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        combidpenerbit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combidpenerbitMouseClicked(evt);
            }
        });
        combidpenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combidpenerbitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ID Buku");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Judul Buku");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Penulis");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("tahun terbit");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ID_penerbit");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Jenis Buku");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Kuantitas");

        btntambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btntambah.setText("add");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnupdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnupdate.setText("update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btndelete.setText("delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        tblbuku.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblbuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Buku", "Judul Buku", "Penulis", "Tahun Terbit", "Jenis Buku", "ID Penerbit", "Kuantitas"
            }
        ));
        tblbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbuku);

        cls.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cls.setText("Clear");
        cls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clsActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setText("DATA BUKU");

        btnreport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnreport.setText("Report");
        btnreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportActionPerformed(evt);
            }
        });

        btnback1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnback1.setText("Back");
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });

        btnback2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnback2.setText("Back");
        btnback2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback2ActionPerformed(evt);
            }
        });

        btncari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(357, 357, 357))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnback1)
                                    .addComponent(btnback2))))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtjudul, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(41, 41, 41)
                                        .addComponent(txtkuantitas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnreport)
                                                .addGap(33, 33, 33)
                                                .addComponent(btncari))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(combidpenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(txtpenulis, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttahun, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(btntambah)))
                                .addGap(35, 35, 35)
                                .addComponent(btnupdate)
                                .addGap(37, 37, 37)
                                .addComponent(btndelete)
                                .addGap(41, 41, 41)
                                .addComponent(cls))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(combidpenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtkuantitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txttahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btntambah)
                            .addComponent(btnupdate)
                            .addComponent(btndelete)
                            .addComponent(cls)
                            .addComponent(btnreport)
                            .addComponent(btncari)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnback2)
                            .addComponent(btnback1))))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
       try{
           
       txtidbuku.setEditable(true);
        int idBuku  = Integer.parseInt(txtidbuku.getText());
        String judulbuku = txtjudul.getText();
        String penulis = txtpenulis.getText();
        String jenis = txtjenis.getText();
        String tahunterbit = txttahun.getText();
        String panjang = combidpenerbit.getSelectedItem().toString();
        String subString = panjang.substring(0,panjang.indexOf("-"));
        int idPenerbit = Integer.parseInt(subString);
        int kuantitas = Integer.parseInt(txtkuantitas.getText());
        Buku buku = new Buku();
        buku.setIdBuku(idBuku);
        buku.setJudulBuku(judulbuku);
        buku.setTahunTerbit(tahunterbit);
        buku.setPenulis(penulis);
        buku.setJenisBuku(jenis);
        buku.setKuantitas(kuantitas);
        buku.setIdPenerbit(idPenerbit);
        
        BukuDAOImp buuk = new BukuDAOImp();
        buuk.insert(buku);
        
        
       }catch(Exception e){
           System.out.println(e);
       }finally{
        showTable();
        clear();
       }
        
        
        
    }//GEN-LAST:event_btntambahActionPerformed

    private void tblbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbukuMouseClicked
        // TODO add your handling code here:
        try {
            int row =tblbuku.getSelectedRow();
            String dataKlik=(tblbuku.getModel().getValueAt(row, 0).toString());
            int idbuku = Integer.parseInt(dataKlik);

            BukuDAOImp dao = new BukuDAOImp();
            Buku bukuDAO = dao.getList(idbuku);
            
            txtidbuku.setText(String.valueOf(bukuDAO.getIdBuku()));
            txtidbuku.setEditable(false);
            txtjudul.setText(bukuDAO.getJudulBuku());
            txtpenulis.setText(bukuDAO.getPenulis());
            txtjenis.setText(bukuDAO.getJenisBuku());
            txttahun.setText(bukuDAO.getTahunTerbit());
            String pilihan = bukuDAO.getIDPenerbit() + "-" + getNamaPenerbit(bukuDAO.getIDPenerbit());
            
            combidpenerbit.getModel().setSelectedItem(pilihan);
           // label1.setText(String.valueOf(bukuDAO.getIDPenerbit()));
            txtkuantitas.setText(String.valueOf(bukuDAO.getKuantitas()));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tblbukuMouseClicked
        public String getNamaPenerbit(int angka){
            String namaPenerbit = "";
           try {
             
             
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/tokobuku_db","root","");
            PreparedStatement pst = cn.prepareStatement("select * from tb_penerbit where id_penerbit=?");
            pst.setInt(1,angka);
            ResultSet rs = pst.executeQuery();
            txtidbuku.setEditable(true);
            while(rs.next()){
          
               
             namaPenerbit = rs.getString("nama_penerbit");
                
            }
            
        } catch (SQLException ex) {
        }
           return namaPenerbit;
        }
    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
         try {
            int productId = Integer.parseInt(txtidbuku.getText());
            String produk = txtjudul.getText();
            txtidbuku.setEditable(true);

            int pesan = JOptionPane.showOptionDialog(this, "Anda yakin akan menghapus buku " +produk+ "?", "Konfirmasi Hapus Buku", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if(pesan == JOptionPane.YES_OPTION){
                Buku product = new Buku();
                product.setIdBuku(productId);
                BukuDAOImp dao = new BukuDAOImp();
                dao.delete(product);
                
                showTable();
                clear();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
         try {

            Buku buku = new Buku();
            int idBuku  = Integer.parseInt(txtidbuku.getText());
            String judulbuku = txtjudul.getText();
            String penulis = txtpenulis.getText();
            String jenis = txtjenis.getText();
            String tahunterbit = txttahun.getText();
            String panjang = combidpenerbit.getSelectedItem().toString();
             String subString = panjang.substring(0,panjang.indexOf("-"));
             int idPenerbit = Integer.parseInt(subString);
            int kuantitas = Integer.parseInt(txtkuantitas.getText());
            txtidbuku.setEditable(true);
           
            buku.setIdBuku(idBuku);
            buku.setJudulBuku(judulbuku);
            buku.setTahunTerbit(tahunterbit);
            buku.setPenulis(penulis);
            buku.setJenisBuku(jenis);
            buku.setKuantitas(kuantitas);
            buku.setIdPenerbit(idPenerbit);
        
            BukuDAOImp dao = new BukuDAOImp();
            dao.update(buku);
            showTable();
            clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void clsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clsActionPerformed
        // TODO add your handling code here:
        clear();
        showTable();
    }//GEN-LAST:event_clsActionPerformed

    private void combidpenerbitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combidpenerbitMouseClicked
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_combidpenerbitMouseClicked

    private void btnreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportActionPerformed
        try {
            txtidbuku.setEditable(true);
            // TODO add your handling code here:
            BukuPDF books = new BukuPDF();
            books.PDF();
        } catch (Exception ex) {
            Logger.getLogger(FormBuku.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            JOptionPane.showMessageDialog(null,"Berhasil dicetak");
        }
    }//GEN-LAST:event_btnreportActionPerformed

    private void btnback2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback2ActionPerformed
        // TODO add your handling code here:
        menuStaff staf = new menuStaff();
        staf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnback2ActionPerformed

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed
        // TODO add your handling code here:
        
         menuSupervisor supervisi = new menuSupervisor();
         supervisi.setVisible(true);
               
        this.setVisible(false);
    }//GEN-LAST:event_btnback1ActionPerformed

    private void combidpenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combidpenerbitActionPerformed
    
            
    }//GEN-LAST:event_combidpenerbitActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
         try{
            String judul = JOptionPane.showInputDialog("Masukkan Judul [PERHATIKAN Uppercase & Lowercase!]");

            BukuDAOImp dao=new  BukuDAOImp() {};
            Buku  bukuDAO=dao.getJudul(judul);
            loadDBByJudul(judul);
              
            txtidbuku.setText(String.valueOf(bukuDAO.getIdBuku()));
            txtidbuku.setEditable(false);
            txtjudul.setText(bukuDAO.getJudulBuku());
            txtpenulis.setText(bukuDAO.getPenulis());
            txtjenis.setText(bukuDAO.getJenisBuku());
            txttahun.setText(bukuDAO.getTahunTerbit());
            String pilihan = bukuDAO.getIDPenerbit() + "-" + getNamaPenerbit(bukuDAO.getIDPenerbit());
            
            combidpenerbit.getModel().setSelectedItem(pilihan);
           // label1.setText(String.valueOf(bukuDAO.getIDPenerbit()));
            txtkuantitas.setText(String.valueOf(bukuDAO.getKuantitas()));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
            
            
    }//GEN-LAST:event_btncariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBuku().setVisible(true);
            }
        });
    }
    public void getCombo(){ //tarik data dari DB untuk combobox
        ArrayList<String>Idx  = new ArrayList<>();
        
         try {
             
             
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/tokobuku_db","root","");
            PreparedStatement pst = cn.prepareStatement("select * from tb_penerbit ");
            ResultSet rs = pst.executeQuery();
            txtidbuku.setEditable(true);
            while(rs.next()){
          
               String namas = rs.getString("id_penerbit");
               String namapenerbit = rs.getString("nama_penerbit");
                combidpenerbit.addItem(namas+"-"+namapenerbit);
            }
            
        } catch (SQLException ex) {
        }
         
         
         
    }
    
   
    public void showTable(){
        try{
        BukuDAOImp buku = new BukuDAOImp();
        List<Buku> listBuku = buku.list();
        DefaultTableModel DFT = (DefaultTableModel) tblbuku.getModel();
        DFT.setRowCount(0);
        for(Buku bukus : listBuku){
            int idBuku = bukus.getIdBuku();
            String judulBuku = bukus.getJudulBuku();
            String penulis = bukus.getPenulis();
            String tahunterbit = bukus.getTahunTerbit();
            String jenisBuku = bukus.getJudulBuku();
            int idPenerbit = bukus.getIDPenerbit();
            int kuantitas = bukus.getKuantitas();
            DFT.addRow(new Object[]{idBuku,judulBuku,penulis,tahunterbit,jenisBuku,idPenerbit,kuantitas});
              
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    public void clear(){
        txtidbuku.setText("");
        txtidbuku.setEditable(true);
        txtjenis.setText("");
        txtjudul.setText("");
        txtkuantitas.setText("");
        txtpenulis.setText("");
        txttahun.setText("");
        combidpenerbit.setSelectedItem(null);
             
    }
    public void loadDBByJudul(String judul){
        try{
            BukuDAOImp bukuDAO = new BukuDAOImp(){};
            List<Buku> listBuku = bukuDAO.listByJudulBuku(judul);
            DefaultTableModel DFT = (DefaultTableModel)tblbuku.getModel();
            DFT.setRowCount(0);
           for(Buku bukus : listBuku){
            int idBuku = bukus.getIdBuku();
            String judulBuku = bukus.getJudulBuku();
            String penulis = bukus.getPenulis();
            String tahunterbit = bukus.getTahunTerbit();
            String jenisBuku = bukus.getJudulBuku();
            int idPenerbit = bukus.getIDPenerbit();
            int kuantitas = bukus.getKuantitas();
            DFT.addRow(new Object[]{idBuku,judulBuku,penulis,tahunterbit,jenisBuku,idPenerbit,kuantitas});
              
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnback1;
    public javax.swing.JButton btnback2;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnreport;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton cls;
    private javax.swing.JComboBox<String> combidpenerbit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JTable tblbuku;
    private javax.swing.JTextField txtidbuku;
    private javax.swing.JTextField txtjenis;
    private javax.swing.JTextField txtjudul;
    private javax.swing.JTextField txtkuantitas;
    private javax.swing.JTextField txtpenulis;
    private javax.swing.JTextField txttahun;
    // End of variables declaration//GEN-END:variables
}
