/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.tokobuku.view;

import com.mycompany.tokobuku.controller.PenerbitDAOImp;
import com.mycompany.tokobuku.login.menuStaff;
import com.mycompany.tokobuku.model.Penerbit;
import com.mycompany.tokobuku.login.menuSupervisor;
import com.mycompany.tokobuku.pdf.PenerbitPDF;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class FormPenerbit extends javax.swing.JFrame {

    /**
     * Creates new form PenerbitForm
     */
    public FormPenerbit() {
        initComponents();
        showTable();
        this.setTitle("Data Penerbit");
        txtid.setEditable(true);
        clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        btnback1 = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblpenerbit = new javax.swing.JTable();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btncari = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnback2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Email");

        btnback1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnback1.setText("Back");
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Data Penerbit Buku");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnadd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        tblpenerbit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Penerbit", "Nama Penerbit", "Email"
            }
        ));
        tblpenerbit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpenerbitMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblpenerbit);

        btnupdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btncari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ID Penerbit");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nama Penerbit");

        btnback2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnback2.setText("Back");
        btnback2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 89, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnback1)
                                    .addComponent(btnback2))
                                .addGap(18, 18, 18)
                                .addComponent(btnadd)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtemail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(140, 140, 140)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnupdate)
                                        .addGap(18, 18, 18)
                                        .addComponent(btndelete)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(btncari)))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnback1)
                        .addComponent(btnback2)
                        .addComponent(btnadd))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnupdate)
                            .addComponent(btndelete)
                            .addComponent(btncari)
                            .addComponent(btnclear)
                            .addComponent(jButton1))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed
        // TODO add your handling code here:
        menuSupervisor visor = new menuSupervisor();
        visor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnback1ActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnclearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            PenerbitPDF penerbitPDF = new PenerbitPDF();
            penerbitPDF.PDF();
        } catch (Exception ex) {
            Logger.getLogger(PetugasForm.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            JOptionPane.showMessageDialog(null,"Berhasil dicetak");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        try{

            txtid.setEditable(true);
            int idPenerbit  = Integer.parseInt(txtid.getText());
            String nama = txtnama.getText();
            String email = txtemail.getText();

            Penerbit penerbit = new Penerbit();
            penerbit.setIdPenerbit(idPenerbit);
            penerbit.setNamaPenerbit(nama);
            penerbit.setEmail(email);

            PenerbitDAOImp terbit = new PenerbitDAOImp();
            terbit.insert(penerbit);

        }catch(Exception e){
            System.out.println(e);
        }finally{
            showTable();
            clear();
        }

    }//GEN-LAST:event_btnaddActionPerformed

    private void tblpenerbitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpenerbitMouseClicked
        // TODO add your handling code here:
        try {
            int row =tblpenerbit.getSelectedRow();
            String dataKlik=(tblpenerbit.getModel().getValueAt(row, 0).toString());
            int idPenerbit = Integer.parseInt(dataKlik);

            PenerbitDAOImp dao = new PenerbitDAOImp();
            Penerbit PenerbitDAO = dao.getPenerbit(idPenerbit);

            txtid.setText(String.valueOf(PenerbitDAO.getIdPenerbit()));
            txtid.setEditable(false);
            txtnama.setText(PenerbitDAO.getNamaPenerbit());
            txtemail.setText(PenerbitDAO.getEmail());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tblpenerbitMouseClicked

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        try {

            Penerbit penerbit = new Penerbit();
            int idPenerbit  = Integer.parseInt(txtid.getText());
            String namaPenerbit = txtnama.getText();
            String email = txtemail.getText();
            txtid.setEditable(true);

            penerbit.setIdPenerbit(idPenerbit);
            penerbit.setNamaPenerbit(namaPenerbit);
            penerbit.setEmail(email);

            PenerbitDAOImp dao = new  PenerbitDAOImp();
            dao.update(penerbit);
            showTable();
            clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        try{
            int id_penerbit=Integer.parseInt(txtid.getText());
            String namaPenerbit=txtnama.getText();

            int pesan=JOptionPane.showOptionDialog(this, "Anda yakin akan menghapus nama penerbit:"+namaPenerbit+"?", "Konfirmasi Hapus Akun Petugas", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if(pesan==JOptionPane.YES_OPTION){
                Penerbit penerbit=new Penerbit();
                penerbit.setIdPenerbit(id_penerbit);
                PenerbitDAOImp dao=new PenerbitDAOImp() {};
                dao.delete(penerbit);
                showTable();
                clear();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btndeleteActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        try{
            String penerbit = JOptionPane.showInputDialog("Masukkan Penerbit Judul [PERHATIKAN Uppercase & Lowercase!]");

            PenerbitDAOImp dao=new  PenerbitDAOImp() {};
            Penerbit  bukuDAO=dao.getNamaPenerbit(penerbit);
            loadDBByNama(penerbit);

            txtid.setText(String.valueOf(bukuDAO.getIdPenerbit()));
            txtid.setEditable(false);
            txtnama.setText(bukuDAO.getNamaPenerbit());
            txtemail.setText(bukuDAO.getEmail());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btncariActionPerformed

    private void btnback2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback2ActionPerformed
        menuStaff staff = new menuStaff();
        staff.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnback2ActionPerformed
    
    public void clear(){
        txtid.setText("");
        txtnama.setText("");
        txtemail.setText("");
        txtid.setEditable(true);

        showTable();
    }

    public void showTable(){
        try{
        PenerbitDAOImp penerbit = new PenerbitDAOImp();
        List<Penerbit> listpenerbit = penerbit.list();
        DefaultTableModel DFT = (DefaultTableModel) tblpenerbit.getModel();
        DFT.setRowCount(0);
        for(Penerbit penerbits : listpenerbit){
            int idPenerbit = penerbits.getIdPenerbit();
            String namaPenerbit = penerbits.getNamaPenerbit();
            String email = penerbits.getEmail();
           
            DFT.addRow(new Object[]{idPenerbit,namaPenerbit,email});
              
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    } 

    public void loadDBByNama(String nama){
        try{
            PenerbitDAOImp penerbitDAO = new  PenerbitDAOImp(){};
            List<Penerbit> listPenerbit = penerbitDAO.listByNamaPenerbit(nama);
            DefaultTableModel DFT = (DefaultTableModel)tblpenerbit.getModel();
            DFT.setRowCount(0);
          for(Penerbit penerbits : listPenerbit){
            int idPenerbit = penerbits.getIdPenerbit();
            String namaPenerbit = penerbits.getNamaPenerbit();
            String email = penerbits.getEmail();
           
            DFT.addRow(new Object[]{idPenerbit,namaPenerbit,email});
              
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenerbit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenerbit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenerbit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenerbit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPenerbit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    public javax.swing.JButton btnback1;
    public javax.swing.JButton btnback2;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblpenerbit;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
