/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tokobuku.view;

import com.mycompany.tokobuku.controller.PetugasDAOImp;
import com.mycompany.tokobuku.model.Petugas;
import com.mycompany.tokobuku.login.menuSupervisor;
import com.mycompany.tokobuku.pdf.PetugasPDF;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class PetugasForm extends javax.swing.JFrame {

    /**
     * Creates new form PetugasForm
     */
    public PetugasForm() {
        initComponents();
        loadDB();
        this.setTitle("Data Petugas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbGroupStatus = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdAkun = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbSupervisor = new javax.swing.JRadioButton();
        rbStaff = new javax.swing.JRadioButton();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePetugas = new javax.swing.JTable();
        cbShowPass = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnReport = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DATA AKUN PETUGAS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Id Akun");

        txtIdAkun.setEditable(false);
        txtIdAkun.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Status");

        rbGroupStatus.add(rbSupervisor);
        rbSupervisor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rbSupervisor.setText("Supervisor");

        rbGroupStatus.add(rbStaff);
        rbStaff.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rbStaff.setText("Staff");

        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCari.setText("CARI");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        tablePetugas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tablePetugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Akun", "Username", "Status"
            }
        ));
        tablePetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePetugasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablePetugas);

        cbShowPass.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbShowPass.setText("Show");
        cbShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPassActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Username");

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        btnReport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReport.setText("REPORT");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnback.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(252, 252, 252))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClear))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbSupervisor)
                                .addGap(30, 30, 30)
                                .addComponent(rbStaff))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtPass)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbShowPass))
                                .addComponent(txtIdAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReport))
                    .addComponent(jScrollPane3))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdAkun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbShowPass)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbSupervisor)
                    .addComponent(rbStaff))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnCari)
                    .addComponent(btnClear)
                    .addComponent(btnReport)
                    .addComponent(btnback))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPassActionPerformed
        if (cbShowPass.isSelected()) {
            txtPass.setEchoChar((char)0);
        }else{
            txtPass.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_cbShowPassActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try{
            Petugas petugas=new Petugas();
            String username=txtUsername.getText();
            String password=txtPass.getText();
            String status;
            if(rbSupervisor.isSelected()){
                status=rbSupervisor.getText();
            }else{
                status=rbStaff.getText();
            }   
            petugas.setUsername(username);
            petugas.setPassword(password);
            petugas.setStatus(status);

            PetugasDAOImp dao=new PetugasDAOImp() {};
            dao.insert(petugas);
            loadDB();
            clearTextField();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        loadDB();
        clearTextField();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tablePetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePetugasMouseClicked
        try{
            int row=tablePetugas.getSelectedRow();
            String dataKlik=(tablePetugas).getModel().getValueAt(row, 0).toString();
            int id_akun = Integer.parseInt(dataKlik);

            PetugasDAOImp dao=new PetugasDAOImp() {};
            Petugas petugasDAO=dao.getPetugas(id_akun);

            txtIdAkun.setText(String.valueOf(petugasDAO.getIdAkun()));
            txtUsername.setText(String.valueOf(petugasDAO.getUsername()));
            txtPass.setText(String.valueOf(petugasDAO.getPassword()));
            //String status_akun=String.valueOf(petugasDAO.getStatus());

            if(String.valueOf(petugasDAO.getStatus()).equals("Supervisor")){
                rbSupervisor.setSelected(true);
            }else{
                rbStaff.setSelected(true);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tablePetugasMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try{
            Petugas petugas=new Petugas();
            int id_akun=Integer.parseInt(txtIdAkun.getText());
            String username=txtUsername.getText();
            String password=txtPass.getText();
            String status;
            if(rbSupervisor.isSelected()){
                status=rbSupervisor.getText();
            }else{
                status=rbStaff.getText();
            }   
            petugas.setUsername(username);
            petugas.setPassword(password);
            petugas.setStatus(status);
            petugas.setIdAkun(id_akun);

            PetugasDAOImp dao=new PetugasDAOImp() {};
            dao.update(petugas);
            loadDB();
            clearTextField();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try{
           int id_akun=Integer.parseInt(txtIdAkun.getText());
            String username=txtUsername.getText();

            int pesan=JOptionPane.showOptionDialog(this, "Anda yakin akan menghapus akun username= "+username+"?", "Konfirmasi Hapus Akun Petugas", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if(pesan==JOptionPane.YES_OPTION){
                Petugas petugas=new Petugas();
                petugas.setIdAkun(id_akun);
                PetugasDAOImp dao=new PetugasDAOImp() {};
                dao.delete(petugas);
                loadDB();;
                clearTextField();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        try{
            String username = JOptionPane.showInputDialog("Masukkan Username [PERHATIKAN Uppercase & Lowercase!]");

            PetugasDAOImp dao=new PetugasDAOImp() {};
            Petugas petugasDAO=dao.getUsername(username);
            loadDBByUsername(username);

            txtIdAkun.setText(String.valueOf(petugasDAO.getIdAkun()));
            txtUsername.setText(String.valueOf(petugasDAO.getUsername()));
            txtPass.setText(String.valueOf(petugasDAO.getPassword()));
            //String status_akun=String.valueOf(petugasDAO.getStatus());

            if(String.valueOf(petugasDAO.getStatus()).equals("Supervisor")){
                rbSupervisor.setSelected(true);
            }else{
                rbStaff.setSelected(true);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        try {
            // TODO add your handling code here:
            PetugasPDF petugasPDF = new PetugasPDF();
            petugasPDF.PDF();
        } catch (Exception ex) {
            Logger.getLogger(PetugasForm.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            JOptionPane.showMessageDialog(null,"Berhasil dicetak");
        }
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        menuSupervisor supervisi = new menuSupervisor();
         supervisi.setVisible(true);
               
        this.setVisible(false);
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetugasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetugasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetugasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetugasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PetugasForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSimpan;
    public javax.swing.JButton btnback;
    private javax.swing.JCheckBox cbShowPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.ButtonGroup rbGroupStatus;
    private javax.swing.JRadioButton rbStaff;
    private javax.swing.JRadioButton rbSupervisor;
    private javax.swing.JTable tablePetugas;
    public javax.swing.JTextField txtIdAkun;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
    public void loadDB(){
        try{
            PetugasDAOImp petugasDAO = new PetugasDAOImp(){};
            List<Petugas> listPetugas=petugasDAO.list();
            DefaultTableModel DFT = (DefaultTableModel)tablePetugas.getModel();
            DFT.setRowCount(0);
            for(Petugas petugas: listPetugas){
                int id_akun=petugas.getIdAkun();
                String username = petugas.getUsername();
                String password=petugas.getPassword();
                String status=petugas.getStatus();
                DFT.addRow(new Object[]{id_akun,username, status});
            }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }

    public void loadDBByUsername(String username){
        try{
            PetugasDAOImp petugasDAO = new PetugasDAOImp(){};
            List<Petugas> listPetugas=petugasDAO.listByUsername(username);
            DefaultTableModel DFT = (DefaultTableModel)tablePetugas.getModel();
            DFT.setRowCount(0);
            for(Petugas petugas: listPetugas){
                int id_akun=petugas.getIdAkun();
                String usernameAkun = petugas.getUsername();
                String password=petugas.getPassword();
                String status=petugas.getStatus();
                DFT.addRow(new Object[]{id_akun,usernameAkun, status});
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void clearTextField(){
        txtIdAkun.setText("");
        txtUsername.setText("");
        txtPass.setText("");
        rbGroupStatus.clearSelection();
    }

}
